POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "anyaaaaa",
  "number": "0149143912"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "0149-143912"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "artur"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "artur",
"number": "0149-143912"
}